---
- hosts: eca
  name: recompile and run ocserv
  vars:
    vpn_name: ocserv-docker
    port: 8443

  tasks:
  - name: update git
    git: repo=https://github.com/wppurking/ocserv-docker.git
         dest=~/ocserv-docker
         force=true

  - name: rebuild docker
    shell: docker build --no-cache -t {{ vpn_name }} .  chdir=~/ocserv-docker

  - name: delete <none> img
    shell: docker images | fgrep '<none>' | xargs docker rmi
    ignore_errors: true

  - name: Stop old ocserv
    shell: docker rm -vf {{ vpn_name }}
    ignore_errors: true

  - name: run new ocserv
    shell: docker run -d --privileged --name {{ vpn_name }} -v ~/ocserv-docker/ocserv:/etc/ocserv -p {{ port }}:443/tcp {{ vpn_name }}
